{{- $fullName := include "go-sample-site.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "go-sample-site.labels" . | nindent 4 }}
  {{- if .Values.ingressClassName }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
  {{- end }}
spec:
  rules:
    - host: "{{ .Values.env }}-{{ $fullName }}.app.8slan.com"
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.port }}
            path: /
